//! The phase half of Wi-Fi channel state, beside the amplitude half in
//! [`super::csi`].
//!
//! A CSI entry is a complex number per subcarrier: [`super::csi`] keeps its
//! magnitude and discards its angle. The angle carries the same motion
//! signal from a different direction -- a body changes the path lengths, and
//! path length is phase -- and it is what every phase-based presence method
//! (and RuView's no-model fallback) measures. This module measures it in
//! fixed point, on the same raw buffer, with nothing new captured.
//!
//! # Binary radians, because the wrap is the point
//!
//! Every angle here is an `i16` in **binary radians**: 65 536 is one turn,
//! so `i16::MIN..=i16::MAX` is one full circle and wrapping arithmetic *is*
//! circular arithmetic. The difference between two neighbouring
//! subcarriers' phases, computed with `wrapping_sub`, is the shortest arc
//! between them -- which is exactly the unwrap step that phase sanitisation
//! needs, for free, with no branch and no `2π` anywhere.
//!
//! # The pipeline, one frame at a time
//!
//! 1. `atan2` per valid subcarrier, from a 257-entry table over one octant
//!    ([`atan2_brad`]; error under 0.15 degrees, measured in the tests).
//! 2. **Sanitise.** Raw CSI phase carries two artefacts that have nothing to
//!    do with the room: a constant offset per frame (carrier frequency
//!    offset) and a slope across subcarriers (sampling time offset). Both
//!    change from frame to frame at random and would swamp any variance.
//!    The standard cleaning is a least-squares line across the subcarriers,
//!    subtracted; what is left is the multipath's own shape.
//!    [`CsiFrame::phases`] does that in integer arithmetic.
//! 3. [`PhaseDetector::push`] keeps the last `W` sanitised phase vectors and
//!    computes, per subcarrier, the **circular variance** over the window:
//!    `1 − |mean of the unit vectors|`, from carried cosine and sine sums
//!    and a 257-entry quarter-wave sine table. Averaged over the
//!    subcarriers, in **parts per million**, it is the phase twin of the
//!    amplitude wander, and the same hysteresis turns it into a [`Verdict`].
//!
//! ppm and not permille because the signal is small. On the ledger's
//! captures an empty room's phase residual jitters by about a degree -- a
//! circular variance near 200 ppm -- and a person walking reads a few
//! hundred to 1 500 ppm. In permille that is the integers 0, 1 and 2.
//!
//! Circular variance rather than a plain standard deviation because the
//! residual is still an angle: a subcarrier hovering around ±half a turn
//! would read as maximally spread to a linear statistic while being
//! perfectly still. Bounded by construction in `[0, 1]`, so the permille is
//! honest at both ends.
//!
//! # What the ledger says about it
//!
//! Derived and checked on the same two ESP32-C6 captures as the amplitude
//! detector (`tests/csi_capture.rs`), against an independent float replica
//! (`tools/csi_phase_oracle.py`). The numbers are in `docs/LEDGER.md`; the
//! thresholds in [`Config::phase_default`] come from them and nowhere else.

use rusty_esp_core::error::Result;
use rusty_esp_core::{Error, Micros};

use super::csi::{CsiFrame, Layout, MAX_SUBCARRIERS, Verdict, isqrt};

/// Thresholds for a [`PhaseDetector`], in parts per million of circular
/// variance.
///
/// Its own type and not [`super::csi::Config`], whose fields are named for
/// permille: a threshold that reads `on_permille: 450` and means ppm is a
/// bug waiting for a reader.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct PhaseConfig {
    /// Phase wander (ppm) at or above which the verdict switches to present.
    pub on_ppm: u32,
    /// Phase wander (ppm) at or below which it may switch back to absent.
    pub off_ppm: u32,
    /// Minimum time the verdict stays present after the last frame above
    /// `on_ppm`.
    pub hold: Micros,
}

impl Default for PhaseConfig {
    /// Set from the same two ESP32-C6 captures as the amplitude defaults
    /// and by the same rule -- `on` at 1.5 × the empty room's ceiling,
    /// `off` just above the ceiling -- with the numbers in `docs/LEDGER.md`.
    /// A product calibrates per room from [`PhaseDetector::wander`].
    fn default() -> Self {
        PhaseConfig {
            on_ppm: 380,
            off_ppm: 260,
            hold: Micros::from_secs(3),
        }
    }
}

/// `atan(i / 256)` for `i` in `0..=256`, in binary radians: `0..=8192`, one
/// octant. Generated by `tools/csi_phase_oracle.py` (`--luts`); the test
/// `the_tables_are_what_the_generator_says` holds them to it.
const ATAN_OCTANT: [u16; 257] = [
    0, 41, 81, 122, 163, 204, 244, 285, 326, 367, 407, 448, 489, 529, 570, 610, 651, 692, 732, 773,
    813, 854, 894, 935, 975, 1015, 1056, 1096, 1136, 1177, 1217, 1257, 1297, 1337, 1377, 1417,
    1457, 1497, 1537, 1577, 1617, 1656, 1696, 1736, 1775, 1815, 1854, 1894, 1933, 1973, 2012, 2051,
    2090, 2129, 2168, 2207, 2246, 2285, 2324, 2363, 2401, 2440, 2478, 2517, 2555, 2594, 2632, 2670,
    2708, 2746, 2784, 2822, 2860, 2897, 2935, 2973, 3010, 3047, 3085, 3122, 3159, 3196, 3233, 3270,
    3307, 3344, 3380, 3417, 3453, 3490, 3526, 3562, 3599, 3635, 3670, 3706, 3742, 3778, 3813, 3849,
    3884, 3920, 3955, 3990, 4025, 4060, 4095, 4129, 4164, 4199, 4233, 4267, 4302, 4336, 4370, 4404,
    4438, 4471, 4505, 4539, 4572, 4605, 4639, 4672, 4705, 4738, 4771, 4803, 4836, 4869, 4901, 4933,
    4966, 4998, 5030, 5062, 5094, 5125, 5157, 5188, 5220, 5251, 5282, 5313, 5344, 5375, 5406, 5437,
    5467, 5498, 5528, 5559, 5589, 5619, 5649, 5679, 5708, 5738, 5768, 5797, 5826, 5856, 5885, 5914,
    5943, 5972, 6000, 6029, 6058, 6086, 6114, 6142, 6171, 6199, 6227, 6254, 6282, 6310, 6337, 6365,
    6392, 6419, 6446, 6473, 6500, 6527, 6554, 6580, 6607, 6633, 6660, 6686, 6712, 6738, 6764, 6790,
    6815, 6841, 6867, 6892, 6917, 6943, 6968, 6993, 7018, 7043, 7068, 7092, 7117, 7141, 7166, 7190,
    7214, 7238, 7262, 7286, 7310, 7334, 7358, 7381, 7405, 7428, 7451, 7475, 7498, 7521, 7544, 7566,
    7589, 7612, 7635, 7657, 7679, 7702, 7724, 7746, 7768, 7790, 7812, 7834, 7856, 7877, 7899, 7920,
    7942, 7963, 7984, 8005, 8026, 8047, 8068, 8089, 8110, 8131, 8151, 8172, 8192,
];

/// `sin` over a quarter turn in 256 steps, scaled to 2^14: `0..=16384`.
///
/// 2^14 and not 2^10, because the quantity this measures is small: a still
/// room's phase residual jitters by about a degree, which is a circular
/// variance near 200 ppm, and a walk reads under 1 500 ppm. A unit vector
/// of 1 024 resolves the mean vector's length to about 1 ‰ -- coarser than
/// the whole signal. At 2^14 the resolution is 61 ppm.
const SIN_QUARTER: [i16; 257] = [
    0, 101, 201, 302, 402, 503, 603, 704, 804, 904, 1005, 1105, 1205, 1306, 1406, 1506, 1606, 1706,
    1806, 1906, 2006, 2105, 2205, 2305, 2404, 2503, 2603, 2702, 2801, 2900, 2999, 3098, 3196, 3295,
    3393, 3492, 3590, 3688, 3786, 3883, 3981, 4078, 4176, 4273, 4370, 4467, 4563, 4660, 4756, 4852,
    4948, 5044, 5139, 5235, 5330, 5425, 5520, 5614, 5708, 5803, 5897, 5990, 6084, 6177, 6270, 6363,
    6455, 6547, 6639, 6731, 6823, 6914, 7005, 7096, 7186, 7276, 7366, 7456, 7545, 7635, 7723, 7812,
    7900, 7988, 8076, 8163, 8250, 8337, 8423, 8509, 8595, 8680, 8765, 8850, 8935, 9019, 9102, 9186,
    9269, 9352, 9434, 9516, 9598, 9679, 9760, 9841, 9921, 10001, 10080, 10159, 10238, 10316, 10394,
    10471, 10549, 10625, 10702, 10778, 10853, 10928, 11003, 11077, 11151, 11224, 11297, 11370,
    11442, 11514, 11585, 11656, 11727, 11797, 11866, 11935, 12004, 12072, 12140, 12207, 12274,
    12340, 12406, 12472, 12537, 12601, 12665, 12729, 12792, 12854, 12916, 12978, 13039, 13100,
    13160, 13219, 13279, 13337, 13395, 13453, 13510, 13567, 13623, 13678, 13733, 13788, 13842,
    13896, 13949, 14001, 14053, 14104, 14155, 14206, 14256, 14305, 14354, 14402, 14449, 14497,
    14543, 14589, 14635, 14680, 14724, 14768, 14811, 14854, 14896, 14937, 14978, 15019, 15059,
    15098, 15137, 15175, 15213, 15250, 15286, 15322, 15357, 15392, 15426, 15460, 15493, 15525,
    15557, 15588, 15619, 15649, 15679, 15707, 15736, 15763, 15791, 15817, 15843, 15868, 15893,
    15917, 15941, 15964, 15986, 16008, 16029, 16049, 16069, 16088, 16107, 16125, 16143, 16160,
    16176, 16192, 16207, 16221, 16235, 16248, 16261, 16273, 16284, 16295, 16305, 16315, 16324,
    16332, 16340, 16347, 16353, 16359, 16364, 16369, 16373, 16376, 16379, 16381, 16383, 16384,
    16384,
];

/// The unit-vector scale of [`SIN_QUARTER`] and of every cosine and sine
/// this module carries.
const UNIT: i32 = 16384;

/// The angle of `(x, y)` in binary radians: `0` along `+x`, `16384` along
/// `+y`, wrapping at a full turn.
///
/// One octant from the table, the rest by symmetry. Both inputs are meant
/// to be small (an ESP32 CSI entry is two `i8`s), but any `i32` works: the
/// ratio is formed as `min * 256 / max`, which cannot overflow for
/// `|v| < 2^23`, and every raw CSI value is inside that by a factor of
/// sixty thousand.
#[must_use]
pub const fn atan2_brad(y: i32, x: i32) -> i16 {
    if x == 0 && y == 0 {
        return 0;
    }
    let ax = x.unsigned_abs();
    let ay = y.unsigned_abs();
    // Within the first octant the table answers directly; in the second the
    // angle is a quarter turn minus the table of the inverse ratio.
    let a: i32 = if ay <= ax {
        ATAN_OCTANT[(ay * 256 / ax) as usize] as i32
    } else {
        16384 - ATAN_OCTANT[(ax * 256 / ay) as usize] as i32
    };
    let a = if x < 0 { 32768 - a } else { a };
    let a = if y < 0 { -a } else { a };
    // 32768 (exactly half a turn) wraps to i16::MIN, which is the same angle.
    a as i16
}

/// `a / b` rounded to nearest, for `b > 0`. Integer `/` truncates toward
/// zero, which for a mean vector is a bias with a sign.
const fn div_round(a: i32, b: i32) -> i32 {
    if a >= 0 {
        (a + b / 2) / b
    } else {
        -((-a + b / 2) / b)
    }
}

/// `(cos, sin)` of a binary-radian angle, each scaled to [`UNIT`].
#[must_use]
const fn unit_vector(angle: i16) -> (i32, i32) {
    // 1024 steps around the circle: the top two bits of the angle are the
    // quadrant, the next eight index the quarter-wave table.
    let a = (angle as u16) >> 6; // 0..1024
    let quadrant = a >> 8;
    let i = (a & 255) as usize;
    let s = SIN_QUARTER[i] as i32;
    let c = SIN_QUARTER[256 - i] as i32;
    match quadrant {
        0 => (c, s),
        1 => (-s, c),
        2 => (-c, -s),
        _ => (s, -c),
    }
}

/// Per-frame sanitised phase, one binary-radian angle per valid subcarrier.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Phases {
    /// The residual phase after the per-frame line is removed, in layout
    /// order; only the first `count` entries are meaningful.
    pub phase: [i16; MAX_SUBCARRIERS],
    /// Valid subcarriers in `phase`.
    pub count: u8,
}

impl Phases {
    /// The valid phases.
    #[must_use]
    pub fn phases(&self) -> &[i16] {
        &self.phase[..self.count as usize]
    }
}

impl CsiFrame<'_> {
    /// Sanitised phase per valid subcarrier of `layout`.
    ///
    /// The raw angles are unwrapped across the subcarriers (the shortest arc
    /// between neighbours, which `wrapping_sub` on binary radians is), then
    /// the least-squares line through them -- the per-frame carrier offset
    /// and sampling-time slope -- is subtracted. What remains is the
    /// channel's own shape, comparable frame to frame.
    ///
    /// `InvalidGeometry` when the buffer is shorter than the layout needs,
    /// or the layout has fewer than two subcarriers (a line needs two
    /// points).
    pub fn phases(&self, layout: &Layout) -> Result<Phases> {
        if self.iq.len() < 2 * layout.entries || layout.count() > MAX_SUBCARRIERS {
            return Err(Error::InvalidGeometry);
        }
        // Raw angles, then unwrapped: `u[k]` is the cumulative shortest-arc
        // walk from `u[0]`, an i32 because it may leave the i16 circle.
        let mut u = [0i32; MAX_SUBCARRIERS];
        let mut n = 0usize;
        let mut prev: i16 = 0;
        for r in layout.valid {
            if r.start >= r.end {
                continue;
            }
            for p in self.iq[2 * r.start..2 * r.end].chunks_exact(2) {
                let im = i32::from(p[0]);
                let re = i32::from(p[1]);
                let raw = atan2_brad(im, re);
                u[n] = if n == 0 {
                    i32::from(raw)
                } else {
                    u[n - 1] + i32::from(raw.wrapping_sub(prev))
                };
                prev = raw;
                n += 1;
            }
        }
        if n < 2 {
            return Err(Error::InvalidGeometry);
        }
        // Least squares over k = 0..n: slope = (n·Σku − Σk·Σu) / (n·Σk² − (Σk)²),
        // intercept = (Σu − slope·Σk) / n. Both in Q16 so the residual keeps
        // sixteen fractional bits until the final shift. `n ≤ 64` and
        // `|u| < 64 · 2^15`, so every product is well inside i64.
        let nn = n as i64;
        let sk: i64 = nn * (nn - 1) / 2;
        let skk: i64 = (nn - 1) * nn * (2 * nn - 1) / 6;
        let mut su: i64 = 0;
        let mut sku: i64 = 0;
        for (k, &v) in u[..n].iter().enumerate() {
            su += i64::from(v);
            sku += k as i64 * i64::from(v);
        }
        let den = nn * skk - sk * sk; // > 0 for n ≥ 2
        let slope_q16 = ((nn * sku - sk * su) << 16) / den;
        let icpt_q16 = ((su << 16) - slope_q16 * sk) / nn;

        let mut out = Phases {
            phase: [0; MAX_SUBCARRIERS],
            count: n as u8,
        };
        for (k, &v) in u[..n].iter().enumerate() {
            let resid_q16 = (i64::from(v) << 16) - slope_q16 * k as i64 - icpt_q16;
            // Back to whole binary radians, then onto the circle. The
            // arithmetic shift rounds toward −∞ uniformly, which a wrap does
            // not care about.
            out.phase[k] = (resid_q16 >> 16) as i16;
        }
        Ok(out)
    }
}

/// Presence from the circular variance of the sanitised phase over the last
/// `W` frames.
///
/// Same shape as [`super::csi::PresenceDetector`]: a ring, sums carried by
/// the one frame that changes, one verdict with hysteresis. The statistic
/// differs -- circular variance instead of a coefficient of variation --
/// because the quantity is an angle.
pub struct PhaseDetector<const W: usize> {
    config: PhaseConfig,
    ring: [[i16; MAX_SUBCARRIERS]; W],
    /// `Σ cos`, `Σ sin` over the ring per subcarrier, in [`UNIT`]s.
    ///
    /// The invariant is `sum == Σ unit_vector(ring[f][sc])` over every slot,
    /// FILLED OR NOT. A zeroed ring is `W` copies of angle 0, whose unit
    /// vector is `(UNIT, 0)` and not `(0, 0)` -- so the sums start at
    /// `(W · UNIT, 0)`. Started at zero, every push into a never-filled slot
    /// subtracted a phantom `(UNIT, 0)`, and the same frame pushed `W` times
    /// read 883 ‰ of variance instead of none. The amplitude detector has no
    /// such trap: an amplitude of 0 contributes 0.
    sum_cos: [i32; MAX_SUBCARRIERS],
    sum_sin: [i32; MAX_SUBCARRIERS],
    count: u8,
    filled: usize,
    next: usize,
    /// Parts per million.
    wander: u32,
    present: bool,
    last_motion: Micros,
    frames: u32,
}

impl<const W: usize> core::fmt::Debug for PhaseDetector<W> {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        f.debug_struct("PhaseDetector")
            .field("window", &W)
            .field("filled", &self.filled)
            .field("wander", &self.wander)
            .field("present", &self.present)
            .field("frames", &self.frames)
            .finish_non_exhaustive()
    }
}

impl<const W: usize> PhaseDetector<W> {
    /// `W` unit vectors of magnitude [`UNIT`] must sum inside an `i32`:
    /// `W · 2^14 < 2^31`, i.e. `W < 2^17`, stated to the compiler.
    const W_FITS_I32_SUM: () = assert!(W < 1 << 17);

    /// A detector with `config`.
    #[must_use]
    pub const fn new(config: PhaseConfig) -> Self {
        PhaseDetector {
            config,
            ring: [[0; MAX_SUBCARRIERS]; W],
            // A zeroed ring is W angles of 0: see the field's note.
            sum_cos: [W as i32 * UNIT; MAX_SUBCARRIERS],
            sum_sin: [0; MAX_SUBCARRIERS],
            count: 0,
            filled: 0,
            next: 0,
            wander: 0,
            present: false,
            last_motion: Micros::ZERO,
            frames: 0,
        }
    }

    /// The thresholds in use.
    #[must_use]
    pub const fn config(&self) -> &PhaseConfig {
        &self.config
    }

    /// Replace the thresholds (calibration) without dropping the window.
    pub fn set_config(&mut self, config: PhaseConfig) {
        self.config = config;
    }

    /// The last computed phase wander, **parts per million**: mean over
    /// subcarriers of `1 000 000 · (1 − |mean unit vector|)` across the
    /// window. The number to log while calibrating a room.
    #[must_use]
    pub const fn wander(&self) -> u32 {
        self.wander
    }

    /// Frames pushed so far.
    #[must_use]
    pub const fn frames(&self) -> u32 {
        self.frames
    }

    /// True once the window holds `W` frames.
    #[must_use]
    pub const fn warm(&self) -> bool {
        self.filled >= W
    }

    /// Forget the window (after a channel change, for instance).
    ///
    /// The ring and the sums are left alone, exactly as the amplitude
    /// detector leaves them: the invariant `sum == Σ ring` must survive a
    /// reset, and it does because neither side is touched.
    pub fn reset(&mut self) {
        self.filled = 0;
        self.next = 0;
        self.count = 0;
        self.wander = 0;
        self.present = false;
    }

    /// Push one frame's sanitised phases taken at `now` and get the verdict.
    pub fn push(&mut self, phases: &Phases, now: Micros) -> Verdict {
        if phases.count == 0 {
            return self.verdict_now();
        }
        if self.filled > 0 && phases.count != self.count {
            self.reset();
        }
        self.count = phases.count;
        let () = Self::W_FITS_I32_SUM;
        // Carry the sums from the one frame that changes: subtract the unit
        // vector of the angle leaving the slot, add the one arriving.
        let new = phases.phases();
        let slot = &mut self.ring[self.next];
        for (sc, (&angle, old)) in new.iter().zip(slot[..new.len()].iter_mut()).enumerate() {
            let (oc, os) = unit_vector(*old);
            let (nc, ns) = unit_vector(angle);
            self.sum_cos[sc] = self.sum_cos[sc] - oc + nc;
            self.sum_sin[sc] = self.sum_sin[sc] - os + ns;
            *old = angle;
        }
        self.next = (self.next + 1) % W;
        if self.filled < W {
            self.filled += 1;
        }
        self.frames = self.frames.wrapping_add(1);
        if self.filled < W {
            return Verdict::Warming;
        }
        self.wander = self.compute_wander();
        if self.wander >= self.config.on_ppm {
            self.present = true;
            self.last_motion = now;
        } else if self.present
            && self.wander <= self.config.off_ppm
            && now.0.saturating_sub(self.last_motion.0) >= self.config.hold.0
        {
            self.present = false;
        }
        self.verdict_now()
    }

    /// `motion` is the wander in **tens of ppm**, clipped to a byte: a walk
    /// on the ledger's captures reads 30–150, a scrambled channel 255.
    const fn verdict_now(&self) -> Verdict {
        if self.filled < W {
            Verdict::Warming
        } else if self.present {
            let tens = self.wander / 10;
            Verdict::Present {
                motion: if tens > 255 { 255 } else { tens as u8 },
            }
        } else {
            Verdict::Absent
        }
    }

    /// Mean over subcarriers of `1 000 000 · (1 − R)`, where `R` is the
    /// length of the mean unit vector over the window for one subcarrier.
    fn compute_wander(&self) -> u32 {
        let n = (self.count as usize).min(MAX_SUBCARRIERS);
        if n == 0 || W == 0 {
            return 0;
        }
        let w = W as i32;
        let mut total: u32 = 0;
        for sc in 0..n {
            // The mean unit vector, each component in −UNIT..=UNIT, so its
            // length is at most UNIT·√2 and the squares fit u32 easily.
            // ROUNDED, not truncated. Every floor here lands on the same
            // side: a shorter mean vector is more variance. Truncating the
            // components and the square root together read a constant
            // +61 ppm above the float replica -- exactly one unit of 2^14 --
            // on both captures, with no scatter. Rounding the division to
            // nearest and taking `isqrt` at double resolution removes it.
            let mc = div_round(self.sum_cos[sc], w);
            let ms = div_round(self.sum_sin[sc], w);
            // |mc|, |ms| ≤ 2^14 (a unit vector to ±1), so mc² + ms² ≤ 2^29
            // and, CAST FIRST, 4× that is 2^31: inside u32, past i32.
            let sq = (mc * mc + ms * ms) as u32;
            let r = (isqrt(4 * sq) as i32 + 1) / 2;
            let r = if r > UNIT { UNIT } else { r };
            // ppm of variance: (UNIT − r) · 10^6 / 2^14, and 10^6 / 2^14 is
            // exactly 15 625 / 256. So one u32 multiply and a shift, exact,
            // where `1_000_000 * (UNIT - r)` is 1.6 × 10^10 at a scrambled
            // channel and overflowed i32 -- caught by the unit test that
            // scrambles one, and only there: a real room never gets past a
            // few thousand. At most 2.56 × 10^8 per subcarrier, 64 of them.
            let d = (UNIT - r) as u32;
            total += (d * 15_625) >> 8;
        }
        total / n as u32
    }
}

#[cfg(test)]
mod tests {
    extern crate std;
    use super::*;
    use std::vec::Vec;

    fn brad_of(y: f64, x: f64) -> f64 {
        y.atan2(x) / core::f64::consts::TAU * 65536.0
    }

    /// Angular distance on the 65 536-brad circle.
    fn dist(a: f64, b: f64) -> f64 {
        let d = (a - b).rem_euclid(65536.0);
        d.min(65536.0 - d)
    }

    #[test]
    fn the_tables_are_what_the_generator_says() {
        for (i, &v) in ATAN_OCTANT.iter().enumerate() {
            let want = (i as f64 / 256.0).atan() / core::f64::consts::TAU * 65536.0;
            assert!(
                (f64::from(v) - want).abs() <= 0.5,
                "atan[{i}] = {v}, want {want}"
            );
        }
        for (i, &v) in SIN_QUARTER.iter().enumerate() {
            let want = (i as f64 / 256.0 * core::f64::consts::FRAC_PI_2).sin() * 16384.0;
            assert!(
                (f64::from(v) - want).abs() <= 0.5,
                "sin[{i}] = {v}, want {want}"
            );
        }
    }

    /// Every (x, y) an i8 CSI entry can hold, against `f64::atan2`.
    #[test]
    fn atan2_brad_is_within_a_table_step_of_float_everywhere() {
        let mut worst = 0.0f64;
        for y in -128i32..=127 {
            for x in -128i32..=127 {
                let got = f64::from(atan2_brad(y, x));
                let want = brad_of(f64::from(y), f64::from(x));
                let d = dist(got, want);
                if d > worst {
                    worst = d;
                }
            }
        }
        // One table step at the flattest point of the octant is
        // atan'(1)/256 turns = 1/(2·256) turns = 128 brads at most; the
        // measured worst case is well under it (printed for the ledger).
        std::println!(
            "atan2_brad worst error over all i8 pairs: {worst:.1} brads ({:.3} deg)",
            worst * 360.0 / 65536.0
        );
        assert!(worst < 64.0, "{worst}");
        // The axes are exact.
        assert_eq!(atan2_brad(0, 100), 0);
        assert_eq!(atan2_brad(100, 0), 16384);
        assert_eq!(atan2_brad(0, -100), i16::MIN);
        assert_eq!(atan2_brad(-100, 0), -16384);
        assert_eq!(atan2_brad(0, 0), 0);
    }

    #[test]
    fn unit_vectors_have_unit_length_and_the_right_quadrant() {
        for k in 0..1024u32 {
            let angle = (k * 64) as u16 as i16;
            let (c, s) = unit_vector(angle);
            let len = ((c * c + s * s) as f64).sqrt();
            assert!(
                (len - 16384.0).abs() <= 2.0,
                "angle {angle}: |({c},{s})| = {len}"
            );
            let want_c = (f64::from(angle) / 65536.0 * core::f64::consts::TAU).cos() * 16384.0;
            let want_s = (f64::from(angle) / 65536.0 * core::f64::consts::TAU).sin() * 16384.0;
            assert!(
                (f64::from(c) - want_c).abs() <= 2.0,
                "{angle}: cos {c} vs {want_c}"
            );
            assert!(
                (f64::from(s) - want_s).abs() <= 2.0,
                "{angle}: sin {s} vs {want_s}"
            );
        }
    }

    /// A frame of I/Q built from a pure line -- offset plus slope across the
    /// subcarriers -- must sanitise to (near) zero everywhere: that line is
    /// exactly the artefact the cleaning removes.
    fn frame_from_angles(angles: &[f64]) -> Vec<i8> {
        let mut iq = std::vec![0i8; 128];
        for (i, k) in Layout::C6_HT20_NATURAL.indices().enumerate() {
            let a = angles[i] / 65536.0 * core::f64::consts::TAU;
            iq[2 * k] = (a.sin() * 100.0).round() as i8; // imaginary first
            iq[2 * k + 1] = (a.cos() * 100.0).round() as i8;
        }
        iq
    }

    #[test]
    fn a_pure_line_sanitises_to_nothing() {
        for (offset, slope) in [
            (0.0, 0.0),
            (12345.0, 0.0),
            (-30000.0, 900.0),
            (5000.0, -2500.0),
        ] {
            let angles: Vec<f64> = (0..56).map(|k| offset + slope * k as f64).collect();
            let iq = frame_from_angles(&angles);
            let frame = CsiFrame {
                timestamp: Micros::ZERO,
                rssi: -40,
                channel: 6,
                iq: &iq,
            };
            let p = frame.phases(&Layout::C6_HT20_NATURAL).expect("layout fits");
            assert_eq!(p.count, 56);
            let worst = p
                .phases()
                .iter()
                .map(|&r| i32::from(r).abs())
                .max()
                .unwrap();
            // The table's angular error and the i8 quantisation of the
            // synthetic vectors leave a few hundred brads (about a degree).
            assert!(
                worst < 700,
                "offset {offset} slope {slope}: residual up to {worst} brads"
            );
        }
    }

    /// A shape that is NOT a line survives sanitisation: the residual keeps
    /// it, up to the line through it.
    #[test]
    fn a_shape_survives_sanitisation() {
        let angles: Vec<f64> = (0..56)
            .map(|k| 3000.0 * ((k as f64) * 0.35).sin() + 1000.0)
            .collect();
        let iq = frame_from_angles(&angles);
        let frame = CsiFrame {
            timestamp: Micros::ZERO,
            rssi: -40,
            channel: 6,
            iq: &iq,
        };
        let p = frame.phases(&Layout::C6_HT20_NATURAL).expect("layout fits");
        let spread = p
            .phases()
            .iter()
            .map(|&r| i32::from(r).abs())
            .max()
            .unwrap();
        assert!(spread > 2000, "the shape was flattened: {spread}");
    }

    #[test]
    fn a_still_channel_is_absent_and_a_scrambled_one_is_present() {
        let iq = frame_from_angles(
            &(0..56)
                .map(|k| 2000.0 * ((k as f64) * 0.4).sin())
                .collect::<Vec<_>>(),
        );
        let frame = CsiFrame {
            timestamp: Micros::ZERO,
            rssi: -40,
            channel: 6,
            iq: &iq,
        };
        let p = frame.phases(&Layout::C6_HT20_NATURAL).unwrap();
        let mut det = PhaseDetector::<8>::new(PhaseConfig::default());
        let mut v = Verdict::Warming;
        for n in 0..8 {
            v = det.push(&p, Micros(n * 20_000));
        }
        assert_eq!(
            v,
            Verdict::Absent,
            "the same frame eight times: {} ppm",
            det.wander()
        );
        // Not exactly zero: the table's unit vectors are unit length to ±1
        // in 16 384, so a perfectly still channel can read a few tens of
        // ppm of pure quantisation. That IS the pipeline's noise floor, and
        // it is a factor of five under an empty room's real reading.
        assert!(
            det.wander() < 100,
            "a still channel: {} ppm of quantisation",
            det.wander()
        );

        // Now eight different, unrelated shapes: the unit vectors point
        // everywhere and the mean vector collapses.
        let mut det = PhaseDetector::<8>::new(PhaseConfig::default());
        let mut v = Verdict::Warming;
        for n in 0..8u64 {
            let angles: Vec<f64> = (0..56)
                .map(|k| 20000.0 * ((k as f64 + n as f64 * 7.0) * 1.7).sin())
                .collect();
            let iq = frame_from_angles(&angles);
            let frame = CsiFrame {
                timestamp: Micros(n * 20_000),
                rssi: -40,
                channel: 6,
                iq: &iq,
            };
            let p = frame.phases(&Layout::C6_HT20_NATURAL).unwrap();
            v = det.push(&p, Micros(n * 20_000));
        }
        assert!(
            matches!(v, Verdict::Present { .. }),
            "scrambled: {v:?} wander {}",
            det.wander()
        );
        assert!(det.wander() > 500_000, "{} ppm", det.wander());
    }

    #[test]
    fn a_count_change_resets_the_window() {
        let iq = frame_from_angles(&std::vec![0.0; 56]);
        let full = CsiFrame {
            timestamp: Micros::ZERO,
            rssi: -40,
            channel: 6,
            iq: &iq,
        }
        .phases(&Layout::C6_HT20_NATURAL)
        .unwrap();
        let legacy = CsiFrame {
            timestamp: Micros::ZERO,
            rssi: -40,
            channel: 6,
            iq: &iq,
        }
        .phases(&Layout::LLTF_20MHZ)
        .unwrap();
        assert_ne!(full.count, legacy.count);
        let mut det = PhaseDetector::<4>::new(PhaseConfig::default());
        for n in 0..4 {
            det.push(&full, Micros(n));
        }
        assert!(det.warm());
        assert_eq!(det.push(&legacy, Micros(5)), Verdict::Warming);
        assert!(!det.warm());
    }
}
